security:
    encoders:
        Appartoo\UserBundle\Entity\Utilisateur: plaintext 

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main_login:
            pattern:   ^/login$
            anonymous: true
        main_register:
            pattern:   ^/register
            anonymous: true			
        main:
            pattern:   ^/
            anonymous: false
            provider:  main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                default_target_path: /
            logout:
                path:   fos_user_security_logout
                target: /login
            remember_me: 
                key:    %secret%